### ISSUE TITLE
Cannot download any source

### ISSUE THREAD

**Issue by samuak8** [isard-vdi/isard#156] opened 2019-05-10 13:49 UTC
Hi, im trying to install some virtual machines on IsardVdi, but Isard do not download any media, the links are correctly input, but i don't why. Do you know any reason for that issue?

Thanks a lot 

![image](https://user-images.githubusercontent.com/37220575/57532049-2f93f080-733b-11e9-8d90-09735d9a9351.png)

**Comment by jvinolas** [comment] 2019-05-16 06:27
Could you check if you have isard-hypervisor Online in hypervisors menu? If it is not online then the problem is there and should be tracked in another way.

**Comment by samuak8** [comment] 2019-05-18 00:10
It's online, but the source aren't running

**Comment by jvinolas** [comment] 2019-05-19 10:24
Are the updates downloading? If you go to updates, can you download domains or media from there?

**Comment by samuak8** [comment] 2019-05-20 18:11
Yes everything is running as normal. Sources wreck, the donwload speed doesn't departure, it's always 0,0/0,0 kb/s

**Comment by NefixEstrada** [comment] 2019-05-21 18:10
Have you tried to cancel it and download it again? It might be a temporary network issue that has turned into this

**Comment by samuak8** [comment] 2019-05-22 08:40
Yes we tried that, and we also tried with several machines, but is an issue
that sometimes appear, and sometimes don't.

**Comment by sim6** [comment] 2020-10-16 08:14
I'm closing this issue due to we need more information to do support but, please, feel free to add more comments if you want more support.

**Closed by sim6** 2020-10-16 08:14 UTC
Labels: area/engine, area/webapp, kind/bug, stage/0-discussion
